all:
install:
	if not exist ..\bin\games\cat mkdir ..\bin\games\cat
	copy cat ..\bin\games\cat
	if not exist ..\bin\games\cat\gfx mkdir ..\bin\games\cat\gfx
	copy cat\gfx ..\bin\games\cat\gfx
	if not exist ..\bin\games\cat\mus mkdir ..\bin\games\cat\mus
	copy cat\mus ..\bin\games\cat\mus
	if not exist ..\bin\games\tutorial2 mkdir ..\bin\games\tutorial2
	copy tutorial2 ..\bin\games\tutorial2
clean:
