clean:
all:	stead.lua

install:
	if not exist ..\bin\stead mkdir ..\bin\stead
	copy stead.lua ..\bin\stead
	copy gui.lua ..\bin\stead
	copy goto.lua ..\bin\stead
	copy xobj.lua ..\bin\stead
	copy input.lua ..\bin\stead
	copy click.lua ..\bin\stead
	copy dbg.lua ..\bin\stead
	copy vars.lua ..\bin\stead
	copy prefs.lua ..\bin\stead
	copy snapshot.lua ..\bin\stead
